web:
  restart: always
  build: ./web/
  expose:
    - "8000"
  links:
    - db:db
    - redis:redis
  env_file: .env
  volumes:
    - ./web:/usr/src/app
  command: /usr/local/bin/gunicorn mydjango.wsgi:application -w 2 -b :8000 --reload

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:web

db:
  restart: always
  build: ./db/
  volumes_from:
    - data
  env_file: .env
  ports:
    - "3306:3306"

redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"

data:
  restart: always
  image: alpine
  volumes:
    - ./db/data:/var/lib/mysql
  command: "true"
